version: '3'
services:
  mongo:
    image: mongo:jessie
    volumes: 
      - ~/docker-volumes/data/mongo:/data/db

  api:
    build: .
    ports: 
      - "8081:8080"
    env_file: .env
    links:
      - mongo